name: ZXP Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install yarn -g
      - run: yarn
      - run: yarn build
      - run: yarn zxp

      - name: GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SOURCE_NAME: ${{ steps.extract_names.outputs.SOURCE_NAME }}
          SOURCE_BRANCH: ${{ steps.extract_names.outputs.SOURCE_BRANCH }}
          SOURCE_TAG: ${{ steps.extract_names.outputs.SOURCE_TAG }}
        with:
          files: ./public/zxp/com.nitro.cep.zxp
